# Generated by Django 4.1 on 2023-06-23 12:03

import booking.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDestinationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '1. RouteDestination',
                'verbose_name_plural': '1. RouteDestination',
            },
        ),
        migrations.CreateModel(
            name='RouteOriginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '1. RouteOrigins',
                'verbose_name_plural': '1. RouteOrigins',
            },
        ),
        migrations.CreateModel(
            name='BusInfosTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=booking.models.BusInfosTable.image_upload_to)),
                ('bus_name', models.CharField(max_length=200, null=True)),
                ('bus_image', models.FileField(null=True, upload_to=booking.models.BusInfosTable.image_upload_to)),
                ('bus_id_number', models.CharField(max_length=200, null=True)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fare', models.CharField(max_length=200, null=True)),
                ('bus_type', models.CharField(choices=[('luxury', 'LUXURY'), ('semi-luxury', 'SEMI-LUXURY')], max_length=200, null=True)),
                ('root_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.routeorigintable')),
            ],
            options={
                'verbose_name': '1. RouteDestination',
                'verbose_name_plural': '1. RouteDestination',
            },
        ),
    ]
