# Generated by Django 4.1 on 2023-06-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businfostable',
            options={'verbose_name': '2. RouteDestination', 'verbose_name_plural': '2. RouteDestination'},
        ),
        migrations.AlterModelOptions(
            name='routedestinationtable',
            options={'verbose_name': '2. RouteDestination', 'verbose_name_plural': '2. RouteDestination'},
        ),
    ]
