# Generated by Django 4.1 on 2023-06-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_businfostable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businfostable',
            options={'verbose_name': '3. RouteDestination', 'verbose_name_plural': '3. RouteDestination'},
        ),
    ]
