# Generated by Django 4.1 on 2023-06-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_businfostable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businfostable',
            options={'verbose_name': '3. bus infos', 'verbose_name_plural': '3. bus infos'},
        ),
    ]
