# Generated by Django 4.1 on 2023-06-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_businfostable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businfostable',
            options={'verbose_name': '3. Bus infos', 'verbose_name_plural': '3. Bus infos'},
        ),
    ]
