# Generated by Django 4.1 on 2023-06-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_businfostable_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfostable',
            name='file',
        ),
    ]
