# Generated by Django 4.1 on 2023-06-23 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_root_origin_businfostable_route_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfostable',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='businfostable',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
