# Generated by Django 4.1 on 2023-06-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_businfostable_departure_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[(0, 'Available'), (1, 'sold')], max_length=200, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.businfostable')),
            ],
            options={
                'verbose_name': '4. Seats',
                'verbose_name_plural': '4. Seats',
            },
        ),
    ]
