# Generated by Django 4.1 on 2023-06-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seats',
            new_name='SeatsTable',
        ),
    ]
