# Generated by Django 4.1 on 2023-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_seats_seatstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatstable',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'sold')], max_length=200, null=True),
        ),
    ]
