# Generated by Django 4.1 on 2023-06-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_bookingtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='seat_id',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.businfostable'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seatstable'),
        ),
    ]
