# Generated by Django 4.1 on 2023-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_bookingtable_bus_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '2. RouteDestination',
                'verbose_name_plural': '2. RouteDestination',
            },
        ),
        migrations.CreateModel(
            name='PickUpsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '2. RouteDestination',
                'verbose_name_plural': '2. RouteDestination',
            },
        ),
    ]
