# Generated by Django 4.1 on 2023-06-24 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_dropstable_options_alter_pickupstable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='drop_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.dropstable'),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='pick_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.pickupstable'),
        ),
    ]
