# Generated by Django 4.1 on 2023-06-24 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_bookingtable_drop_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='safari_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
