# Generated by Django 4.2.2 on 2023-07-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_bookingtable_safari_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeorigintable',
            options={'verbose_name': '0. RouteOrigins', 'verbose_name_plural': '0. RouteOrigins'},
        ),
        migrations.AlterField(
            model_name='seatstable',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'sold')], null=True),
        ),
        migrations.CreateModel(
            name='BookingStateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('BOOKED', 'BOOKED'), ('CONFIRMED', 'CONFIRMED'), ('CANCELED', 'CANCELLED')], default='BOOKED', max_length=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtable')),
            ],
            options={
                'verbose_name': '1. Booking state',
                'verbose_name_plural': '1. Booking state',
            },
        ),
    ]
