# Generated by Django 4.2.2 on 2023-07-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_routeorigintable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstatetable',
            options={'verbose_name': '7. Booking state', 'verbose_name_plural': '7. Booking state'},
        ),
        migrations.AlterModelOptions(
            name='bookingtable',
            options={'verbose_name': '6. Tickets', 'verbose_name_plural': '6. Tickets'},
        ),
        migrations.AlterModelOptions(
            name='businfostable',
            options={'verbose_name': '4. Bus infos', 'verbose_name_plural': '4. Bus infos'},
        ),
        migrations.AlterModelOptions(
            name='dropstable',
            options={'verbose_name': '9. Drop points ', 'verbose_name_plural': '9. Drop points '},
        ),
        migrations.AlterModelOptions(
            name='pickupstable',
            options={'verbose_name': '8. Pick Up points', 'verbose_name_plural': '8. Pick Up points'},
        ),
        migrations.AlterModelOptions(
            name='seatstable',
            options={'verbose_name': '5. Seats', 'verbose_name_plural': '5. Seats'},
        ),
        migrations.CreateModel(
            name='OriginDestinationRoutesTabale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.routeorigintable')),
                ('routes', models.ManyToManyField(to='booking.routedestinationtable')),
            ],
            options={
                'verbose_name': '3. RouteDestination',
                'verbose_name_plural': '3. RouteDestination',
            },
        ),
    ]
