# Generated by Django 4.2.2 on 2023-07-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_bookingstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeorigintable',
            options={'verbose_name': '0. RouteOrigins', 'verbose_name_plural': '0. RouteOrigins'},
        ),
    ]
