# Generated by Django 4.2.2 on 2023-07-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_bookingstatetable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origindestinationroutestabale',
            options={'verbose_name': '3. Origin Route Destinations routes', 'verbose_name_plural': '3. Origin Route Destinations routes'},
        ),
    ]
