# Generated by Django 4.2.2 on 2023-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_rename_bookingstate_bookingstatetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatetable',
            name='state',
            field=models.IntegerField(choices=[(0, 'BOOKED'), (1, 'CONFORMED'), (2, 'CANCELLED')], default=1),
        ),
    ]
