# Generated by Django 4.2.2 on 2023-07-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_bookingstatetable_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingstatetable',
            old_name='booking',
            new_name='booking_id',
        ),
    ]
