# Generated by Django 4.2.2 on 2023-07-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_rename_booking_bookingstatetable_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingstatetable',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
