# Generated by Django 4.2.2 on 2023-07-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_alter_bookingstatetable_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatetable',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtable'),
        ),
    ]
