# Generated by Django 4.2.2 on 2023-07-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_alter_bookingstatetable_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatetable',
            name='state',
            field=models.CharField(choices=[('BOOKED', 'BOOKED'), ('CONFIRMED', 'CONFIRMED'), ('CANCELED', 'CANCELLED')], default=0, max_length=10),
        ),
    ]
