# Generated by Django 4.2.2 on 2023-07-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_bookingstatetable_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstatetable',
            name='state',
        ),
    ]
